apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pm-storage-pvc
spec:
  accessModes:
    - ReadWriteMany # Required for scaling app/horizon pods
  resources:
    requests:
      storage: 10Gi
  # storageClassName: efs-sc # Example for AWS EFS
